final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('question.urls')),
]

question/urls.py
from django.urls import path
from question import views
from django.contrib import admin

urlpatterns = [
    path('create', views.create),
    path('show/', views.show),
    path('edit/<int:id>/', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>/', views.delete),

]

question/models.py
from django.db import models
# Create your models here.

class Question(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=400)
    pub_date = models.DateField('date published')
    type_choices = (
        ('General', 'General'),
        ('Advance', 'Advance'),
        ('Professional', 'Professional'),
    )
    type = models.CharField(max_length=200, choices=type_choices)

    def __str__(self):
        return self.title

question/forms.py
from django import forms
from question.models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = "__all__"

question/views.py
from question.models import Question
from question.forms import QuestionForm
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
# Create your views here.

def create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show/')
            except:
                pass
    else:
        form = QuestionForm()
    return render(request, 'question/index.html', {'form': form})

def show(request):
    question = Question.objects.all()
    return render(request, "question/show.html", {'question': question})

def edit(request,id):
    question = Question.objects.get(id = id)
    return render(request, 'question/edit.html', {'question': question})

def update(request, id):
    question = Question.objects.get(id=id)
    form = QuestionForm(request.POST, instance = question)
    # print(id)
    if form.is_valid():
        form.save()
        # print("Hello")
        return redirect("/show/")
    return render(request, 'question/edit.html', {'question': question})

def delete(request,id):
    question = Question.objects.get(id = id)

    if request.method == "POST":
        question.delete()
        return redirect("/show")
    return render(request, 'question/delete.html', {'question': question})

question/templates/question/delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="">
    <title>Delete</title>
  </head>
  <body>
    <div class="container">
      <form method="post">
          {% csrf_token %}
        Are you sure you want to delete "{{ question.id }}" ?
        <input class="btn btn-primary" type="submit" value="Submit" />
      </form>
    </div>
  </body>
</html>

question/templates/question/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
    {% load static %}
</head>
<body>
<form method="POST" class="post-form" action="/update/{{question.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Title</label>
    <div class="col-sm-4">
        <label for="id_title"></label><input type="text" name="text" id="id_title" required maxlength="200" value="{{ question.title }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-4">
         <label for="id_description"></label><input type="text" name="description" id="id_description" required maxlength="400" value="{{ question.description }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Publication Date:</label>
    <div class="col-sm-4">
         <label for="id_pub_date"></label><input type="text" name="pub_date" id="id_pub_date" required maxlength="100" value="{{ question.pub_date }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Type</label>
    <div class="col-sm-4">
        <label for="id_type"></label><input type="text" name="type" id="id_type" required maxlength="200" value="{{ question.type }}" />
    </div>
    </div>
      <div class="form-group row">
      <label class="col-sm-1 col-form-label"></label>
      <div class = "col-sm-4">
      <button type="submit" class="btn btn-success">Update</button>
    </div>
   </div>
    </div>
</form>
</body>
</html>

question/templates/question/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/create">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Title</label>
    <div class="col-sm-4">
      {{ form.title }}
    </div>
  </div>
     <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-4">
      {{ form.description }}
    </div>
  </div>
     <div class="form-group row">
     <label class="col-sm-2 col-form-label">Publication Date</label>
     <div class="col-sm-4">
        {{ form.pub_date }}
    </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Type</label>
    <div class="col-sm-4">
      {{ form.type }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

question/templates/question/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show</title>
     {% load static %}
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Published Date</th>
        <th>Type</th>
    </tr>
    </thead>
    <tbody>
{% for question in question %}
    <tr>
        <td>{{ question.title }}</td>
        <td>{{ question.description }}</td>
        <td>{{ question.pub_date }}</td>
        <td>{{ question.type }}</td>
        <td>
            <a href="/edit/{{ question.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ question.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
</body>
</html>